using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CreditWorks.VehicleManagement.Modules.Categories.Entities;

/// <summary>
/// An icon a category can use. Icons are reference data: changing one here changes it for every
/// category that uses it.
/// </summary>
[Table("CategoryIcon", Schema = "categories")]
[Index(nameof(Key), IsUnique = true)]
public class CategoryIcon
{
    /// <summary>The longest key the Key column holds.</summary>
    public const int KeyMaxLength = 50;

    /// <summary>Primary key, generated by SQL Server (IDENTITY) starting at 1.</summary>
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int Id { get; set; }

    /// <summary>What the API calls the icon, such as "car". A category's "icon" is set to this key.</summary>
    [MaxLength(KeyMaxLength)]
    public string Key { get; set; } = "";

    /// <summary>
    /// The icon image as SVG markup. Clients must display it through an <c>&lt;img&gt;</c> element,
    /// never by inserting the markup into the page, so any script inside an SVG can't run.
    /// </summary>
    public string Svg { get; set; } = "";
}
