using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using CreditWorks.VehicleManagement.Shared.Persistence;
using Microsoft.EntityFrameworkCore;

namespace CreditWorks.VehicleManagement.Modules.Categories.Entities;

/// <summary>
/// A vehicle weight category. A vehicle belongs to the category where
/// <c>MinWeightKg &lt;= weight &lt; MaxWeightKg</c> (lower-inclusive, upper-exclusive).
/// <para>
/// Unique names, unique ranges and a single open-ended category are rules across rows, so they're checked by
/// <c>CategoryRules</c> rather than by unique indexes (see <c>CategoriesDbContext</c>).
/// </para>
/// </summary>
[Table("Categories", Schema = "categories")]
public class Category
{
    // The name column's size, defined once here. The column uses it, and so do the rules in CategoryRules, so the
    // two can't disagree. The weight columns use the shared WeightColumn format, the same as vehicle weights.

    /// <summary>The longest name the Name column holds.</summary>
    public const int NameMaxLength = 50;

    /// <summary>Primary key, generated by SQL Server (IDENTITY) when a category is inserted.</summary>
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int Id { get; set; }

    [MaxLength(NameMaxLength)]
    public string Name { get; set; } = "";

    [Precision(WeightColumn.Precision, WeightColumn.Scale)]
    public decimal MinWeightKg { get; set; }

    /// <summary>Exclusive upper bound. Null only for the heaviest category, which has no upper limit.</summary>
    [Precision(WeightColumn.Precision, WeightColumn.Scale)]
    public decimal? MaxWeightKg { get; set; }

    /// <summary>Foreign key to <see cref="CategoryIcon"/>.</summary>
    public int IconId { get; set; }

    /// <summary>An icon can't be deleted while a category uses it.</summary>
    [DeleteBehavior(DeleteBehavior.Restrict)]
    public CategoryIcon Icon { get; set; } = null!;
}
