using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CreditWorks.VehicleManagement.Modules.Vehicles.Entities;

/// <summary>
/// A vehicle manufacturer, such as Mazda. Manufacturers are reference data kept in the database, not in code.
/// </summary>
[Table("Manufacturers", Schema = "vehicles")]
[Index(nameof(Name), IsUnique = true)]
public class Manufacturer
{
    /// <summary>The longest name the Name column holds.</summary>
    public const int NameMaxLength = 50;

    /// <summary>Primary key, generated by SQL Server (IDENTITY) when a manufacturer is inserted.</summary>
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int Id { get; set; }

    [MaxLength(NameMaxLength)]
    public string Name { get; set; } = "";
}
