using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using CreditWorks.VehicleManagement.Shared.Persistence;
using Microsoft.EntityFrameworkCore;

namespace CreditWorks.VehicleManagement.Modules.Vehicles.Entities;

/// <summary>
/// A vehicle. It has no category column: the category is calculated from <see cref="WeightKg"/> each time
/// the vehicle is read, so changing the categories recategorises every vehicle at once.
/// </summary>
[Table("Vehicles", Schema = "vehicles")]
public class Vehicle
{
    // Defined once here: the columns and check constraints use them, and so do the rules in VehicleRules, so they
    // can't disagree. The weight column uses the shared WeightColumn format, the same as category boundaries.

    /// <summary>The longest owner name the OwnerName column holds (the frontend has the same limit).</summary>
    public const int OwnerNameMaxLength = 100;

    /// <summary>The earliest year of manufacture: 1886, the year of the first petrol car (the Benz Patent-Motorwagen).</summary>
    public const int EarliestYear = 1886;

    /// <summary>How many years ahead the year of manufacture may be: next year's models go on sale this year.</summary>
    public const int YearsAheadAllowed = 1;

    /// <summary>Primary key, generated by SQL Server (IDENTITY) when a vehicle is inserted.</summary>
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int Id { get; set; }

    [MaxLength(OwnerNameMaxLength)]
    public string OwnerName { get; set; } = "";

    /// <summary>Foreign key to <see cref="Manufacturer"/>. Required, so every vehicle has a manufacturer.</summary>
    public int ManufacturerId { get; set; }

    /// <summary>
    /// A manufacturer can't be deleted while a vehicle uses it. Deleting a vehicle never affects its manufacturer.
    /// </summary>
    [DeleteBehavior(DeleteBehavior.Restrict)]
    public Manufacturer Manufacturer { get; set; } = null!;

    public int YearOfManufacture { get; set; }

    /// <summary>
    /// Weight in kilograms. The column keeps 2 decimal places but SQL Server silently rounds anything finer,
    /// so the "at most 2 decimal places" rule is checked in code before saving.
    /// </summary>
    [Precision(WeightColumn.Precision, WeightColumn.Scale)]
    public decimal WeightKg { get; set; }
}
